import React from "react";
import {
  ImageOverlay,
  TileLayer,
  CaptureMap,
  SyncMapGroup,
  MapContainer,
  GeoJsonLayer,
  InnerText,
  CustomMarker,
  CustomPolygon,
  CustomCircle,
  CustomMultiPoint,
  CustomRectangle,
  ControlSection,
  TextMarker,
  CustomPolyLine,
  LayerGroup,
  MultiPointDrawButton,
  PointDrawButton,
  PolygonDrawButton,
  PolylineDrawButton,
  RectangleDrawButton,
  SyncMap,
  TextDrawButton,
  DeleteAnnotation,
  ModifyAnnotation,
  MoveAnnotation,
  Button,
  CompassWheel,
  DrawingTools,
  FullScreenFeature,
  ZoomFeature,
  useMap,
  useMapEventHandler,
  useMapRotation,
  useSelectAnnotation,
  getProfileFromFeature,
  icon,
  ControlGroup,
  ImageOveray,
} from "react-openlayers7";
// Add react-live imports you need here

const ReactLiveScope = {
  React,
  ...React,
  TileLayer,
  SyncMapGroup,
  SyncMap,
  ImageOverlay,
  MapContainer,
  GeoJsonLayer,
  CaptureMap,
  LayerGroup,
  InnerText,
  CustomMarker,
  CustomPolygon,
  CustomCircle,
  CustomMultiPoint,
  CustomRectangle,
  ControlSection,
  TextMarker,
  CustomPolyLine,
  MultiPointDrawButton,
  PointDrawButton,
  PolygonDrawButton,
  PolylineDrawButton,
  RectangleDrawButton,
  TextDrawButton,
  DeleteAnnotation,
  ModifyAnnotation,
  MoveAnnotation,
  Button,
  CompassWheel,
  DrawingTools,
  FullScreenFeature,
  ZoomFeature,
  useMap,
  useMapEventHandler,
  useMapRotation,
  useSelectAnnotation,
  getProfileFromFeature,
  icon,
  ControlGroup,
  ImageOveray,
};

ReactLiveScope.icon.marker = "/img/marker-basic.png";
ReactLiveScope.icon.selected = "/img/marker-selected.png";
export default ReactLiveScope;
