import React from 'react';
import { TileLayer, 
  Map,
  GeoJsonLayer,
  InnerText,
  CustomMarker,
  CustomPolygon,
  CustomCircle,
  CustomMultiPoint,
  CustomRectangle,
  ControlSection,
  TextMarker,
  LayerGroup,
  MultiPointDrawButton,
  PointDrawButton,
  PolygonDrawButton,
  PolylineDrawButton,
  RectangleDrawButton,
  TextDrawButton,
  DeleteAnnotation,
  ModifyAnnotation,
  MoveAnnotation,
  Button,
  CompassWheel,
  DrawingTools,
  FullScreenFeature,
  ZoomFeature,
  useMap,
  useMapEventHandler,
  useMapRotation,
  useSelectAnnotation,
  getProfileFromFeature,
  icon
 } from "react-openlayers7";
// Add react-live imports you need here





const ReactLiveScope = {
  React,
  ...React,
  TileLayer, 
  Map,
  GeoJsonLayer,
  LayerGroup,
  InnerText,
  CustomMarker,
  CustomPolygon,
  CustomCircle,
  CustomMultiPoint,
  CustomRectangle,
  ControlSection,
  TextMarker,
  MultiPointDrawButton,
  PointDrawButton,
  PolygonDrawButton,
  PolylineDrawButton,
  RectangleDrawButton,
  TextDrawButton,
  DeleteAnnotation,
  ModifyAnnotation,
  MoveAnnotation,
  Button,
  CompassWheel,
  DrawingTools,
  FullScreenFeature,
  ZoomFeature,
  useMap,
  useMapEventHandler,
  useMapRotation,
  useSelectAnnotation,
  getProfileFromFeature,
  icon,
};

ReactLiveScope.icon.marker = '/img/marker-icon.png'
export default ReactLiveScope;
