/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "React-Openlayers7",
  "tagline": "React-Openlayers7 guide",
  "favicon": "img/favicon.ico",
  "url": "https://main--incredible-otter-643bc8.netlify.app",
  "baseUrl": "/",
  "organizationName": "Han-D-Peter",
  "projectName": "react-openlayer-official",
  "stylesheets": [
    "react-openlayers7/dist/index.css"
  ],
  "onBrokenLinks": "ignore",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "remarkPlugins": [
            [
              null,
              {
                "sync": true
              }
            ]
          ],
          "sidebarPath": "/Users/jaesunghan/react-openlayer-official/sidebars.js",
          "editUrl": "https://github.com/Han-D-Peter/react-openlayer-official/tree/main/docs/"
        },
        "pages": {
          "remarkPlugins": [
            null
          ]
        },
        "blog": {
          "remarkPlugins": [
            [
              null,
              {
                "converters": [
                  "pnpm"
                ]
              }
            ]
          ],
          "showReadingTime": true,
          "editUrl": "https://github.com/Han-D-Peter/react-openlayer-official/tree/main/blog/"
        },
        "theme": {
          "customCss": "/Users/jaesunghan/react-openlayer-official/src/css/custom.css"
        }
      }
    ]
  ],
  "themes": [
    "@docusaurus/theme-live-codeblock"
  ],
  "themeConfig": {
    "image": "img/logo.webp",
    "navbar": {
      "title": "react-openlayers7",
      "logo": {
        "alt": "rect-openlayers7 logo",
        "src": "img/logo.webp"
      },
      "items": [
        {
          "to": "/docs/Getting%20started/intro",
          "label": "Getting Started",
          "position": "left"
        },
        {
          "to": "/docs/category/guide",
          "label": "Guide",
          "position": "left"
        },
        {
          "href": "https://github.com/Han-D-Peter/react-openlayer",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Docs",
              "to": "/docs/intro"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/Han-D-Peter/react-openlayer"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 React-Openlayers7 Project, Inc. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "This will error"
        }
      ],
      "additionalLanguages": []
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
